"""rename department

Revision ID: 282bc2ee93d7
Revises: c2d6b2a917a2
Create Date: 2023-12-06 21:17:22.360072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '282bc2ee93d7'
down_revision = 'c2d6b2a917a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('deparment', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'deparment')
    # ### end Alembic commands ###
